### ISSUE TITLE
Issue with a JS line

### ISSUE THREAD

**Issue by dlannan-fmad** [unifire-app/aspect#6]
I have been trying to render a multiple javascript lines: 
```
<script type="text/javascript" src="{{www_dir}}assets/js/vendors/jquery-3.2.1.min.js"></script>
<script type="text/javascript" src="{{www_dir}}assets/js/vendors/bootstrap.min.js"></script>
<script type="text/javascript" src="{{www_dir}}assets/js/vendors/bootstrap-slider.min.js"></script>
<script type="text/javascript" src="{{www_dir}}assets/js/vendors/modernizr-2.6.2.custom.min.js"></script>
<script type="text/javascript" src="{{www_dir}}assets/js/scripts.min.js"></script>
<script type="text/javascript" src="{{www_dir}}assets/js/Tween.js"></script>
<script type="text/javascript" src="{{www_dir}}/assets/js/vendors/driver.min.js"></script>
```
With some stylesheets above this. When I remove the js lines, the render works fine (of course with missing js errors). 
There is no error - it exits normally, but it only renders to the end of the very first JS line. 

This is a twig template included in a basic html template. Simple html, head, body, main and footer. The twig included file is in the head (I wonder if this is a problem). 
Here is roughly how it is included (removed some set objects etc - removing these dont fix it):
```
<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
{{ include('templates/viewer/head.html.twig', with_context = true) }}
</head>
<body>
<div id="main" role="main">
</div><!-- /#main -->

<div class="footer-wrapper">
  <footer role="contentinfo">
  </footer>
</div><!-- /.footer-wrapper -->
</body>
</html>
```
Id expect the render pass or the display pass to be able to render this quite easily. 
![image](https://user-images.githubusercontent.com/60128766/90337557-5eab0e80-e022-11ea-9102-1b47d8a1145b.png)

Desktop
 - OS: Debian 10
 - Browser Chromium CEF (Its running 6 months behind - trying to stay on a stable track).
 - Version 79.0.394.130_linux64

Running in a Luajit 2.1 interpreter. No Open Resty, or Nginx involved here. Just Luajit.

Any help with this would be appreciated. Im sure its something weird Im doing (first time user of Aspect - heavy user of Twig). 
www_dir is set in the render. And Im using:
```
    local output, err = aspect:render(fullpath, { 
        page=page, www_dir=www_dir, site=site 
    })
```
To call it with aspect initialized with no config - {} 
Loader initialized with appropriate directory (files are loading in fine).

**Comment by bzick** [comment]
- You can show debug information via `bin/aspect` ?
  ```bash
  bin/aspect --dump path/to/template.twig 
  ```
  there we can see the template code.
- `err` is `nil`?

**Comment by dlannan-fmad** [comment]
Hi. Thanks for the quick response. Yes err is nil. I'll do a debug run and post. Im wondering if its chromium security stopping js inclusion or something weird like that. I will output the data that gets sent to chromium as well.

**Comment by dlannan-fmad** [comment]
Ok. really sorry about this. I should have checked sooner. 
The output render string is exactly correct.
It looks like chromium is doing something very weird. I'll close. Thanks again for your swift response - really appreciate it. And great work with Aspect, I hope I can help out with it going forward.
